{% set name = "types-click-spinner" %}
{% set version = "0.1.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-click-spinner-{{ version }}.tar.gz
  sha256: 9d27089f7fbc1dcb391ee143b62a36d71e35a14f94b893b6abcf6f360492a751

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/click_spinner-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for click-spinner
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
